---
framework: jest
postMerge:
  pattern:
    - "./test/**/*.spec.ts"
    - "./test/*.spec.ts"
preMerge:
  pattern:
    - "./test/**/*.spec.ts"
    - "./test/*.spec.ts"
preRun:
     command:
        - npm install
        - npm run build
postRun:
     command:
        - node --version
version: 1.3
